### ISSUE TITLE
Issue importing safer (macosx)

### ISSUE THREAD

**Issue by imorti** [arthurtyukayev/python-safer#10]
Big fan of this as their APIs are not documented so great work. However: 

   ```from safer import CompanySnapshot
ModuleNotFoundError: No module named 'safer' ```

On Python 3.7.4. MacOSX. Installed using `pip install python-safer` is instructed. 

when I run a `pip list | grep safer` it only shows python-safer. 

Now, when I try to run with ```import python-safer``` etc I get this: 

  File "main.py", line 1
    from python-safer import CompanySnapshot
               ^
SyntaxError: invalid syntax

**Comment by justJay-dev** [comment]
you were right the first time, it should be 
`from safer import CompanySnapshot`

Could be several things including weirdness with osx and python2/homebrew. I go through this a lot! My first suggestion / question would be can you do a fresh venv and try?

`python3 -m venv env`

`source env/bin/activate`
`pip3 install python-safer`

`touch whatever.py`
edit whatever.py and add
`from safer import CompanySnapshot`

`client = CompanySnapshot()`
`results = client.search('python')`
`for company in results:`
   `print(company)`

and then 
`python3 run whatever.py`

reply back with your output? I'd love to help with this!

**Comment by imorti** [comment]
Yeah, it was basically an issue with running inside vscode terminal. I got it to run great so well done. However, I notice it doesn't do real-time data like when you hit the portal. the APIs seem to have a delay. DM me at @imorti if you know a good way to get portal data. Thanks Jay!

**Comment by imorti** [comment]
Closing issue as this was python env thing.
