### ISSUE TITLE
Question about data results

### ISSUE THREAD

**Issue by ph3l1x** [arthurtyukayev/python-safer#2]
It seems that as soon as a number is entered into the system you can use the portal and search it. It will only return the company name. But it seems about after 24 hours when searching https://safer.fmcsa.dot.gov/CompanySnapshot.aspx it will then contain all the info about the USDOT number. Is there a way to get this data immediately without having to wait 24 hours?

**Comment by arthurtyukayev** [comment]
@ph3l1x python-safer will only search what is available in the Safer system.
This package reads the website just like you would if you were browsing it.

Does that make sense?

**Comment by ph3l1x** [comment]
Yes very much so. Do you know if there is a way to access the data quicker?
I know if someone that has a script that can access the data immediately.
Or of some type of an API. Only asking because there isn't much you about
that site on the internet anywhere and you seen to be the only one I could
find that's worked with their system. Just thought I would ask, and thank
you for your time and responding to me.

Ryan

**Comment by arthurtyukayev** [comment]
Depending on the exact data that you're looking for there is another government website that has DOT data, it's the FMCSA's SMS (Simple Measurement System).

They might be listing data faster than the Safer system, but I've never actually checked. You can view company at this link, I randomly searched a company:
https://ai.fmcsa.dot.gov/SMS/Carrier/604262/Overview.aspx

This package doesn't support the SMS system, but it can easily be written.
